// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxKYz4jQjlaWheCEDDq45FncSZR5K_Uzc',
    appId: '1:724697991487:web:0e2ec0f830261f7973ab8a',
    messagingSenderId: '724697991487',
    projectId: 'flutter-iti-1e6f5',
    authDomain: 'flutter-iti-1e6f5.firebaseapp.com',
    storageBucket: 'flutter-iti-1e6f5.firebasestorage.app',
    measurementId: 'G-TDBXTHQ4QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMbJ0EjnK8HpJTHHeQX0kWi3ZQtybNjGY',
    appId: '1:724697991487:android:e0a297c5a9a6985473ab8a',
    messagingSenderId: '724697991487',
    projectId: 'flutter-iti-1e6f5',
    storageBucket: 'flutter-iti-1e6f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW0fE5XxoODxp78tbCTksRkbHW6jwzeeg',
    appId: '1:724697991487:ios:5cc377996fed7c3c73ab8a',
    messagingSenderId: '724697991487',
    projectId: 'flutter-iti-1e6f5',
    storageBucket: 'flutter-iti-1e6f5.firebasestorage.app',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW0fE5XxoODxp78tbCTksRkbHW6jwzeeg',
    appId: '1:724697991487:ios:5cc377996fed7c3c73ab8a',
    messagingSenderId: '724697991487',
    projectId: 'flutter-iti-1e6f5',
    storageBucket: 'flutter-iti-1e6f5.firebasestorage.app',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxKYz4jQjlaWheCEDDq45FncSZR5K_Uzc',
    appId: '1:724697991487:web:f56705a4f415a66b73ab8a',
    messagingSenderId: '724697991487',
    projectId: 'flutter-iti-1e6f5',
    authDomain: 'flutter-iti-1e6f5.firebaseapp.com',
    storageBucket: 'flutter-iti-1e6f5.firebasestorage.app',
    measurementId: 'G-8HMT0TMY86',
  );
}
